language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: bionic
env:
  global:
    - DEPOPTS="*"
    - TESTS=true
    - DISTRO=ubuntu-18.04
  matrix:
    - OCAML_VERSION=4.03 PACKAGE="zmq"       PINS="zmq:."
    - OCAML_VERSION=4.03 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
    - OCAML_VERSION=4.03 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
    - OCAML_VERSION=4.08 PACKAGE="zmq"       PINS="zmq:."
    - OCAML_VERSION=4.08 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
    - OCAML_VERSION=4.08 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
    - OCAML_VERSION=4.09 PACKAGE="zmq"       PINS="zmq:."
    - OCAML_VERSION=4.09 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
    - OCAML_VERSION=4.09 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
os:
  - linux
